### ISSUE TITLE
Incorrect js

### ISSUE THREAD

**Issue by alexovchinnicov** [webdetails/pentahoLanguagePacks#140]
<img width="342" alt="image" src="https://user-images.githubusercontent.com/39153933/39876975-d9bcda5c-549e-11e8-9d0a-81737c60d409.png">

**Comment by carlosrusso** [comment]
I _think_ you will need to build the packages  using "ant", and use the output zips to get rid of this problem.

**Comment by alexovchinnicov** [comment]
ANT build the project without errors. I resolved the problem as change cyrillic letters to javascript escape characters.
<img width="421" alt="image" src="https://user-images.githubusercontent.com/39153933/39903853-6e2ffd1c-54ff-11e8-9409-cf966c5f72f5.png">
