### ISSUE TITLE
Error in marketplace URL

### ISSUE THREAD

**Issue by dguiarj** [webdetails/pentahoLanguagePacks#143]
Pentaho 8.2
marketplace url: 
https://github.com/webdetails/pentahoLanguagePacks/releases/download/8.2-18.12.06/languagePack_pt_BR-8.2-18.12.06.zip

Real url:
https://github.com/webdetails/pentahoLanguagePacks/releases/download/untagged-1f48a81fe3a77eb51cfd/languagePack_pt_BR-8.2-18.12.06.zip

It seems that the release lost its TAG.

**Comment by pamval** [comment]
This is fixed! Thank you.
